### ISSUE TITLE
TODO for v.1.0

### ISSUE THREAD

**Issue by pbelskiy** [pbelskiy/aiojenkins#3]
- [ ] remove function stubs from readme, try to use readthedocs.io hook 
- [ ] black code formatter
- [x] use conftest for Jenkins instance and fixtures for tmpdir (pytest)
- [x] add stubs (mypy hook for stubs?)
- [x] use jenkins.utils through public interface only
- [x] internal retrier when network problem \ server rebooting
- [x] reuse aiohttp client session -> https://github.com/pbelskiy/aiojenkins/pull/5
- [x] builds.start -> builds.build? %) -> jobs.build() ?
- [x] remove code duplication in requests part
- [x] use POST for build_job
- [x] nodes CRUD
- [x] fix flake8 notes
- [x] add crumb live updater
- [x] add wait is_jenkins_ready function & use it in tests instead of dumb sleep
- [x] token API support 
- [x] add isort to CI
- [x] use submodules for nodes, jobs etc
- [x] CI: mypy
- [x] problem with default parameters build (use buildWithParameters) if parameters exist
- [x] return build queue id
- [x] remove leading slash (GET //job/test_build_list_1595076834.379972/api/json?tree=allBuilds%5Bnumber,url%5D HTTP/1.1 )
- [x] get rid off code duplication in tests (job create \ delete)
---
Fully engineered entities:
- [x] nodes
- [x] jobs
- [x] builds
